const workContent = [
  {
    url: 'can-i-have-this-dance',
    ratio: '100%',
    src: 'work/can-i-have-this-dance-720.jpg',
    srcset:
      'work/can-i-have-this-dance-480.jpg 480w, work/can-i-have-this-dance-720.jpg 720w, work/can-i-have-this-dance-1080.jpg 1080w',
    alt: "Can I Have This Dance's artwork",
    title: 'Can I Have This Dance',
    description: `Single by Lie Ning.`,
    tags: 'Mix, Master',
    path: '/work?project=can-i-have-this-dance',
    mediaTitle: 'Can I Have This Dance EP by Anyma by Richie Hawtin',
    mediaSrc: 'https://open.spotify.com/embed/track/4AohQfg4HFitXqj7UXuZrT',
    year: 2021,
    credits: [
      { role: 'Vocals by', people: 'Lie Ning' },
      { role: 'Wriring', people: 'Lie Ning, Parisi & David Sneddon' },
      { role: 'Production', people: 'Parisi' },
      { role: 'Mix & Master', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'realm-of-consciousness-pt-v',
    ratio: '100%',
    src: 'work/realm-of-consciousness-pt-v-720.jpg',
    srcset:
      'work/realm-of-consciousness-pt-v-480.jpg 480w, work/realm-of-consciousness-pt-v-720.jpg 720w, work/realm-of-consciousness-pt-v-1080.jpg 1080w',
    alt: "Realm of Consciousness PT.V's artwork",
    title: 'Realm of Consciousness PT.V',
    description: `Album by Afterlife various artists.`,
    tags: 'Mix, Master',
    path: '/work?project=realm-of-consciousness-pt-v',
    mediaTitle: 'Realm of Consciousness PT.V by Afterlife various artists',
    mediaSrc: 'https://open.spotify.com/embed/album/0bDVQCKj9ElT4JrzcvYnoR',
    mediaHeight: 400,
    year: 2021,
    credits: [
      {
        role: 'Music by',
        people:
          'Colyn, Innellea, Recondite, Patrice Bäumel, Joseph Capriati, Stephan Jolk, Fideles, Hunter/Game, Primal, Marino Canal, AE:THER, Dyzen, Agents of Time, Tone Depth, Fedele, Gardens of God & Beswerda',
      },
      { role: 'Sogno Profondo mixed by', people: 'Nadoki Studios' },
      { role: 'Master', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli', 'Elia Bertolaso'],
  },
  {
    url: 'acid-king',
    ratio: '100%',
    src: 'work/acid-king-720.jpg',
    srcset:
      'work/acid-king-480.jpg 480w, work/acid-king-720.jpg 720w, work/acid-king-1080.jpg 1080w',
    alt: "Acid King's artwork",
    title: 'Acid King',
    description: `EP by Richie Hawtin.`,
    tags: 'Master',
    path: '/work?project=acid-king',
    mediaTitle: 'Acid King EP by Anyma by Richie Hawtin',
    mediaSrc: 'https://open.spotify.com/embed/album/2bPCREAXZxEudTJkLJrvNW',
    mediaHeight: 240,
    year: 2021,
    credits: [
      { role: 'Produced and Mixed by', people: 'Richie Hawtin' },
      { role: 'Master', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'claire',
    ratio: '100%',
    src: 'work/claire-720.jpg',
    srcset:
      'work/claire-480.jpg 480w, work/claire-720.jpg 720w, work/claire-1080.jpg 1080w',
    alt: "Claire's artwork",
    title: 'Claire',
    description: `EP + NFT drop by Anyma.`,
    tags: 'Mix, Master',
    path: '/work?project=claire',
    mediaTitle: 'Claire by Anyma',
    mediaSrc: 'https://open.spotify.com/embed/album/7cCOKtUAAyXgCa8oIdqU34',
    mediaHeight: 180,
    year: 2021,
    credits: [
      { role: 'Music by', people: 'Anyma' },
      { role: 'Mix & Master', people: 'Nadoki Studios' },
      { role: 'Visuals by', people: 'IOR50 Studio' },
    ],
    teamMembers: ['Julia Borelli', 'Elia Bertolaso'],
  },
  {
    url: 'awakening',
    ratio: '100%',
    src: 'work/awakening-720.jpg',
    srcset:
      'work/awakening-480.jpg 480w, work/awakening-720.jpg 720w, work/awakening-1080.jpg 1080w',
    alt: "Awakening's artwork",
    title: 'Awakening',
    description: `Single by AVAWAVES.`,
    tags: 'Mix',
    path: '/work?project=awakening',
    mediaTitle: 'Awakening by AVAWAVES',
    mediaSrc: 'https://open.spotify.com/embed/track/1YpzzmCzKzwwvOH0XRBhO8',
    year: 2021,
    credits: [
      { role: 'Music by', people: 'AVAWAVES' },
      { role: 'Mix', people: 'Nadoki Studios' },
      { role: 'Master', people: 'Zino Mikorey' },
      { role: 'Artwork by', people: 'Carla Music' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'triptidethud',
    ratio: '100%',
    src: 'work/triptidethud-720.jpg',
    srcset:
      'work/triptidethud-480.jpg 480w, work/triptidethud-720.jpg 720w, work/triptidethud-1080.jpg 1080w',
    alt: "The Prey's artwork",
    title: 'TripTideThud',
    description: `Plastikman's soundtrack for Prada's SS22 Menswear show.`,
    tags: 'Master',
    path: '/work?project=triptidethud',
    mediaTitle:
      'Miuccia Prada and Raf Simons present Prada SS22 menswear collection',
    mediaSrc: 'https://www.youtube.com/embed/sxK9_kotE1Y',
    year: 2021,
    credits: [
      { role: 'Music by', people: 'Platikman/Richie Hawtin' },
      { role: 'Master', people: 'Nadoki Studios' },
      { role: 'Co-creative Directors', people: 'Raf Simons & Miuccia Prada' },
      { role: 'Set design', people: 'OMA' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'sentient',
    ratio: '100%',
    src: 'work/sentient-720.jpg',
    srcset:
      'work/sentient-480.jpg 480w, work/sentient-720.jpg 720w, work/sentient-1080.jpg 1080w',
    alt: "Sentient's artwork",
    title: 'Sentient',
    description: `Anyma's project debut EP.`,
    tags: 'Mix, Master',
    path: '/work?project=sentient',
    mediaTitle: 'Anyma - Sentient',
    mediaSrc: 'https://open.spotify.com/embed/album/53E9q0Gu0d3ROPgFKwSSNg',
    mediaHeight: 210,
    year: 2021,
    credits: [
      { role: 'Music by', people: 'Anyma' },
      { role: 'Mix & Master', people: 'Nadoki Studios' },
      { role: 'Artwork by', people: 'plusyes' },
    ],
    teamMembers: ['Julia Borelli', 'Elia Bertolaso'],
  },
  {
    url: 'invisible-wires',
    ratio: '100%',
    src: 'work/invisible-wires-720.jpg',
    srcset:
      'work/invisible-wires-480.jpg 480w, work/invisible-wires-720.jpg 720w, work/invisible-wires-1080.jpg 1080w',
    alt: "Invisible Wires' artwork",
    title: 'Invisible Wires',
    description: `Drusnoise's EP.`,
    tags: 'Mix',
    path: '/work?project=invisible-wires',
    mediaTitle: 'Invisible Wires by Drusnoise',
    mediaSrc: 'https://open.spotify.com/embed/album/2T5tV08nBMPC1bXrjiutUf',
    mediaHeight: 180,
    year: 2021,
    credits: [
      { role: 'Music by', people: 'Drusnoise' },
      { role: 'Mix', people: 'Nadoki Studios' },
      { role: 'Master', people: 'Conor Dalton at Glowcast Mastering' },
      { role: 'Artwork', people: 'Bertha Abslalon' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'doomscrolling',
    ratio: '100%',
    src: 'work/doomscrolling-720.jpg',
    srcset:
      'work/doomscrolling-480.jpg 480w, work/doomscrolling-720.jpg 720w, work/doomscrolling-1080.jpg 1080w',
    alt: "The Prey's artwork",
    title: 'Doomscrolling',
    description: `Stil & Bense's EP.`,
    tags: 'Master',
    path: '/work?project=doomscrolling',
    mediaTitle: 'Doomscrolling by Still & Bense',
    mediaSrc: 'https://open.spotify.com/embed/album/7FM6rDlWokL8N9gHScKsN6',
    mediaHeight: 210,
    year: 2021,
    credits: [
      { role: 'Music & Mix by', people: 'Still & Bense' },
      { role: 'Remixes by', people: 'Lorraine & GNTN' },
      { role: 'Master', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'syntax',
    ratio: '100%',
    src: 'work/syntax-720.jpg',
    srcset:
      'work/syntax-480.jpg 480w, work/syntax-720.jpg 720w, work/syntax-1080.jpg 1080w',
    alt: "Syntax's artwork",
    title: 'Syntax',
    description: `F.U.S.E., Richie Hawtin EP.`,
    tags: 'Master',
    path: '/work?project=syntax',
    mediaTitle: 'Syntax by F.U.S.E./Richie Hawtin',
    mediaSrc: 'https://open.spotify.com/embed/album/7cJczMBsxFc5byfCeSMrxN',
    mediaHeight: 160,
    year: 2021,
    credits: [
      { role: 'Music & Mix by', people: 'Richie Hawtin' },
      { role: 'Visuals by', people: 'Matthew Hawtin' },
      { role: 'Master', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'deserve-it',
    ratio: '100%',
    src: 'work/deserve-it-720.jpg',
    srcset:
      'work/deserve-it-480.jpg 480w, work/deserve-it-720.jpg 720w, work/deserve-it-1080.jpg 1080w',
    alt: "Deserve it's artwork",
    title: 'Deserve it',
    description: `Nicolas Sales' single.`,
    tags: 'Master',
    path: '/work?project=deserve-it',
    mediaTitle: 'deserve it by Nicolas Sales',
    mediaSrc: 'https://open.spotify.com/embed/track/0Gngbm5XMkZCWVoQp4RCIf',
    year: 2021,
    credits: [
      { role: 'Music & Mix by', people: 'Nicolas Sales' },
      { role: 'Master', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'fatbulous',
    ratio: '100%',
    src: 'work/fatbulous-720.jpg',
    srcset:
      'work/fatbulous-480.jpg 480w, work/fatbulous-720.jpg 720w, work/fatbulous-1080.jpg 1080w',
    alt: "Fatbulous's artwork",
    title: 'Fatbulous',
    description: `Dornika's debut single.`,
    tags: 'Master',
    path: '/work?project=fatbulous',
    mediaTitle: 'Fatbulous by Dornika',
    mediaSrc: 'https://open.spotify.com/embed/track/41Pl90RIquJRbHOlgRsKj2',
    year: 2021,
    credits: [
      { role: 'Songwriting & Concept', people: 'Dornika' },
      { role: 'Mix', people: 'Gil Hockman' },
      { role: 'Master', people: 'Nadoki Studios' },
      { role: 'Photography', people: 'David Kavaler' },
      { role: 'Outfit', people: 'Lupae' },
      { role: 'MUA', people: 'Arabinda Des' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'acid-drop',
    ratio: '100%',
    src: 'work/acid-drop-720.jpg',
    srcset:
      'work/acid-drop-480.jpg 480w, work/acid-drop-720.jpg 720w, work/acid-drop-1080.jpg 1080w',
    alt: "Acid Drop's artwork",
    title: 'Acid Drop',
    description: `Plastikman's first NFT collection.`,
    tags: 'Master',
    path: '/work?project=acid-drop',
    mediaTitle: '',
    mediaSrc: '',
    year: 2021,
    credits: [
      { role: 'Produced & Mixed by', people: 'Richie Hawtin' },
      { role: 'Master', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'the-prey',
    ratio: '100%',
    src: 'work/the-prey-720.jpg',
    srcset:
      'work/the-prey-480.jpg 480w, work/the-prey-720.jpg 720w, work/the-prey-1080.jpg 1080w',
    alt: "The Prey's artwork",
    title: 'The Prey',
    description: `Mind Against remix of Monolink's single "The Prey".`,
    tags: 'Mix, Master',
    path: '/work?project=the-prey',
    mediaTitle: 'The Prey by Monolink remixed by Mind Against.',
    mediaSrc: 'https://open.spotify.com/embed/track/3sMQ55H79frDZG6TXam3UC',
    year: 2021,
    credits: [
      { role: 'Original by', people: 'Monolink' },
      { role: 'Remixed by', people: 'Mind Against' },
      { role: 'Mix & Master', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli', 'Elia Bertolaso'],
  },
  {
    url: 'genesys',
    ratio: '100%',
    src: 'work/genesys-720.jpg',
    srcset:
      'work/genesys-480.jpg 480w, work/genesys-720.jpg 720w, work/genesys-1080.jpg 1080w',
    alt: "Genesys' artwork",
    title: 'Genesys',
    description: 'Genesys announcement communication',
    tags: 'Mix, Master',
    path: '/work?project=genesys',
    mediaTitle: 'Genesys announcement communication by Anyma',
    mediaSrc: 'https://www.instagram.com/p/CPilEVfhv2r/embed/',
    year: 2021,
    credits: [
      { role: 'Music by', people: 'Anyma' },
      { role: 'Mix & Master', people: 'Nadoki Studios' },
      { role: 'Visuals by', people: `Builder's Club and Plusyes` },
    ],
    teamMembers: ['Julia Borelli', 'Elia Bertolaso'],
  },
  {
    url: 'not-your-type',
    ratio: '100%',
    src: 'work/not-your-type-720.jpg',
    srcset:
      'work/not-your-type-480.jpg 480w, work/not-your-type-720.jpg 720w, work/not-your-type-1080.jpg 1080w',
    alt: 'Not Your Type artwork',
    title: 'Not Your Type',
    description: "Sunmoon's third single.",
    tags: 'Master',
    path: '/work?project=not-your-type',
    mediaTitle: 'Not Your Type by Sunmoon',
    mediaSrc: 'https://open.spotify.com/embed/track/53DCpHFCGzaIyaxZCnqXyA',
    year: 2021,
    credits: [
      { role: 'Produced by', people: 'Sunmoon' },
      { role: 'Vocals by', people: 'Sine' },
      { role: 'Master', people: 'Nadoki Studios' },
      { role: 'Released on', people: 'Vybrant' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'curvas-peligrosas',
    ratio: '100%',
    src: 'work/curvas-peligrosas-720.jpg',
    srcset:
      'work/curvas-peligrosas-480.jpg 480w, work/curvas-peligrosas-720.jpg 720w, work/curvas-peligrosas-1080.jpg 1080w',
    alt: `Curvas Peligrosas' artwork`,
    title: 'Curvas Peligrosas',
    description: "Seleminga's second EP.",
    tags: 'Mix, Master',
    path: '/work?project=curvas-peligrosas',
    mediaTitle: 'Curvas Peligrosas by Seleminga',
    mediaSrc: 'https://open.spotify.com/embed/album/4fC6hSYFlNnFAnuTEjDi5q',
    mediaHeight: 240,
    year: 2021,
    credits: [
      { role: 'Music by', people: 'Seleminga' },
      { role: 'Mix & Master', people: 'Nadoki Studios' },
      { role: 'Artwork by', people: 'Synopsies' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'new-era',
    ratio: '100%',
    src: 'work/new-era-720.jpg',
    srcset:
      'work/new-era-480.jpg 480w, work/new-era-720.jpg 720w, work/new-era-1080.jpg 1080w',
    alt: `New Era's artwork`,
    title: 'New Era',
    description: 'Stephan Jolk & Yotto first collaborative EP.',
    tags: 'Master',
    path: '/work?project=new-era',
    mediaTitle: 'New Era EP by Yotto & Stephan Jolk',
    mediaSrc: 'https://open.spotify.com/embed/album/49LqNtUITrajPTnpwyC8tA',
    mediaHeight: 160,
    year: 2021,
    credits: [
      { role: 'Produced by', people: 'Yotto + Stephan Jolk' },
      { role: 'Master', people: 'Nadoki Studios' },
      { role: 'Released on', people: 'Afterlife' },
    ],
    teamMembers: ['Julia Borelli', 'Elia Bertolaso'],
  },
  {
    url: 'close-my-eyes',
    ratio: '100%',
    src: 'work/close-my-eyes-720.jpg',
    srcset:
      'work/close-my-eyes-480.jpg 480w, work/close-my-eyes-720.jpg 720w, work/close-my-eyes-1080.jpg 1080w',
    alt: `Close My Eyes' artwork`,
    title: 'Close My Eyes',
    description: "Sunmoon's second single.",
    tags: 'Master',
    path: '/work?project=close-my-eyes',
    mediaTitle: 'Close My Eyes by Sunmoon',
    mediaSrc: 'https://open.spotify.com/embed/track/4NfAu7GSDDumt9rQr2vEUZ',
    year: 2021,
    credits: [
      { role: 'Produced by', people: 'Sunmoon' },
      { role: 'Vocals by', people: 'Sine' },
      { role: 'Master', people: 'Nadoki Studios' },
      { role: 'Released on', people: 'Afterlife' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'london',
    ratio: '100%',
    src: 'work/london-720.jpg',
    srcset:
      'work/london-480.jpg 480w, work/london-720.jpg 720w, work/london-1080.jpg 1080w',
    alt: `London's artwork`,
    title: 'London',
    description: `Giana Brotherz remix of John Johnson's "London".`,
    tags: 'Stem Master',
    path: '/work?project=london',
    mediaTitle: 'London remix by the Giana Brotherz',
    mediaSrc: 'https://open.spotify.com/embed/track/0DFnifjOEoLu21jsaWucHq',
    year: 2021,
    credits: [
      { role: 'Original by', people: 'John Johnson' },
      { role: 'Remixed by', people: 'Giana Brotherz' },
      { role: 'Stem Master', people: 'Nadoki Studios' },
      { role: 'Released on', people: 'Iconyc' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'nina',
    ratio: '100%',
    src: 'work/nina-720.jpg',
    srcset:
      'work/nina-480.jpg 480w, work/nina-720.jpg 720w, work/nina-1080.jpg 1080w',
    alt: `Niña's artwork`,
    title: 'Niña',
    description: "Seleminga's single.",
    tags: 'Mix, Master',
    path: '/work?project=nina',
    mediaTitle: 'Niña by Seleminga',
    mediaSrc: 'https://open.spotify.com/embed/track/4gI3kTtsxftTB4mBOX133P',
    year: 2021,
    credits: [
      { role: 'Music by', people: 'Seleminga' },
      { role: 'Mix & Master', people: 'Nadoki Studios' },
      { role: 'Artwork by', people: 'Mert Akbal' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'inxtro',
    ratio: '100%',
    src: 'work/inxtro-720.jpg',
    srcset:
      'work/inxtro-480.jpg 480w, work/inxtro-720.jpg 720w, work/inxtro-1080.jpg 1080w',
    alt: `Inxtro's artwork`,
    title: 'Inxtro',
    description:
      "Plastikman's soundtrack for the Prada Fall/Winter 2021 Womanswear Collection runway show.",
    tags: 'Master',
    path: '/work?project=inxtro',
    mediaTitle:
      'Prada Fall/Winter 21 Womens Collection – A conversation with Miuccia Prada and Raf Simons to follow',
    mediaSrc: 'https://www.youtube.com/embed/yKw39s55vOM',
    year: 2021,
    credits: [
      { role: 'Music & Mix by', people: 'Richie Hawtin' },
      { role: 'Master', people: 'Nadoki Studios' },
      { role: 'Writer, Director & Producer', people: 'Lee Daniels' },
      { role: 'Co-Creative Directors', people: 'Raf Simons & Miuccia Prada' },
      { role: 'Fashion Designer', people: 'Rem Koolhaas' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'unity-part-two',
    ratio: '100%',
    src: 'work/unity-part-two-720.jpg',
    srcset:
      'work/unity-part-two-480.jpg 480w, work/unity-part-two-720.jpg 720w, work/unity-part-two-1080.jpg 1080w',
    alt: `Unity Part 2's artwork`,
    title: 'Unity PT. 2',
    description: `Second part of Afterlife's "Unity" compilation.`,
    tags: 'Master',
    path: '/work?project=unity-part-two',
    mediaTitle: 'Unity Pt.2 by varius Afterlife artists',
    mediaSrc: 'https://open.spotify.com/embed/album/5FkWjMTGQOhag93NyFfLP6',
    mediaHeight: 360,
    year: 2021,
    credits: [
      { role: 'Tracks by', people: 'Mind Against, SOEL & Massano' },
      { role: 'Mastered by', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'yum-yum',
    ratio: '100%',
    src: 'work/yum-yum-720.jpg',
    srcset:
      'work/yum-yum-480.jpg 480w, work/yum-yum-720.jpg 720w, work/yum-yum-1080.jpg 1080w',
    alt: `Yum Yum's artwork`,
    title: 'YUM YUM',
    description: `Copycattz remix of Laura Blue's debut single "Yum Yum".`,
    tags: 'Master',
    path: '/work?project=yum-yum',
    mediaTitle: 'YUM YUM remix by Copycattz',
    mediaSrc: 'https://open.spotify.com/embed/track/0uLKiRpmdumNTldHjeisDS',
    year: 2021,
    credits: [
      { role: 'Original by', people: 'Laura Blue' },
      { role: 'Remixed by', people: 'Copycattz' },
      { role: 'Master', people: 'Nadoki Studios' },
      { role: 'Released on', people: 'Vybrant' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'tequilla-and-lime',
    ratio: '100%',
    src: 'work/tequilla-and-lime-720.jpg',
    srcset:
      'work/tequilla-and-lime-480.jpg 480w, work/tequilla-and-lime-720.jpg 720w, work/tequilla-and-lime-1080.jpg 1080w',
    alt: `Tequilla & Lime's artwork`,
    title: 'Tequilla & Lime',
    description: "Sunmoon's debut single.",
    tags: 'Master',
    path: '/work?project=tequilla-and-lime',
    mediaTitle: 'Tequila & Lime by Sunmoon',
    mediaSrc: 'https://open.spotify.com/embed/track/13mWorFtWgmyrR6VAYVrlK',
    year: 2021,
    credits: [
      { role: 'Produced by', people: 'Sunmoon' },
      { role: 'Vocals by', people: 'Joseph Feinstein' },
      { role: 'Master', people: 'Nadoki Studios' },
      { role: 'Released on', people: 'Vybrant' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'va-01',
    ratio: '100%',
    src: 'work/va-01-720.jpg',
    srcset:
      'work/va-01-480.jpg 480w, work/va-01-720.jpg 720w, work/va-01-1080.jpg 1080w',
    alt: `Various Artists Volume I's artwork`,
    title: 'Various Artists Volume I',
    description: 'First compilation of the Gothenburg-based collective STRECK.',
    tags: 'Master',
    path: '/work?project=va-01',
    mediaTitle: 'Various Artits Volume I by the STRECK collective',
    mediaSrc:
      'https://www.youtube.com/embed/videoseries?list=PL1ntfXx-b2MwesGDjM19uGYNDdaosiGkB',
    year: 2021,
    credits: [
      {
        role: 'Music by',
        people:
          'Stefán, Rogue Wave, Stina Francina, Neoandra, Sima, Sonic, Kal Ket & Pro Athlete',
      },

      { role: 'Master', people: 'Nadoki Studios' },
      { role: 'Artwork', people: 'Radu Gota' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'non-citizens',
    ratio: '100%',
    src: 'work/non-citizens-720.jpg',
    srcset:
      'work/non-citizens-480.jpg 480w, work/non-citizens-720.jpg 720w, work/non-citizens-1080.jpg 1080w',
    alt: "Frame from the Jordi Garcia Rodriguez's 'Non-Citizens' documentary",
    title: 'Non-Citizens',
    description:
      "Jordi Garcia Rodriguez's documentary about the Central African refugee crisis.",
    tags: 'Mix, Master',
    path: '/work?project=non-citizens',
    mediaTitle: 'Non-Citizens - Trailer',
    mediaSrc: 'https://player.vimeo.com/video/442164701',
    year: 2020,
    credits: [
      {
        role: 'Directed, Written & Filmed by',
        people: 'Jordi Garcia Rodriguez',
      },

      { role: 'Music by', people: 'Leon Gurvitch' },
      { role: 'Cast & VO', people: 'Lucie Aron' },
      { role: 'On set sound', people: 'Ted Debit' },
      { role: 'VO Recording', people: 'Louis Mcguire' },
      { role: 'Subtitles', people: 'Lyz Pfister' },
      { role: 'Translations', people: 'Flora Beillouin & Juliette Ferrere' },
      { role: 'Mix & Master', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli', 'João Rodrigues'],
  },
  {
    url: 'unity-live',
    ratio: '100%',
    src: 'work/unity-live-720.jpg',
    srcset:
      'work/unity-live-480.jpg 480w, work/unity-live-720.jpg 720w, work/unity-live-1080.jpg 1080w',
    alt: "Unity Live's artwork",
    title: 'Unity Live',
    description: "Afterlife's livestream series.",
    tags: 'Audio Engineering',
    path: '/work?project=unity-live',
    mediaTitle: '"Unity Live livestream series by varius Afterlife artists',
    mediaSrc:
      'https://www.youtube.com/embed/videoseries?list=PLvmn9Ssy7H3zRe6XrCYPoUykVso4wmXbg',
    year: 2021,
    credits: [
      { role: 'Episode 1', people: 'Tale of Us' },
      { role: 'Episode 2', people: 'Fideles' },
      { role: 'Episode 3', people: 'Denis Horvat' },
      { role: 'Episode 4', people: 'Mind Against' },
      { role: 'Episode 5', people: 'Stephan Jolk' },
      { role: 'Episode 6', people: 'Mathame' },
      { role: 'Episode 7', people: 'Agents of Time' },
      { role: 'Audio Engineering', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli', 'Elia Bertolaso'],
  },
  {
    url: 'holiday-special',
    ratio: '100%',
    src: 'work/holiday-special-720.jpg',
    srcset:
      'work/holiday-special-480.jpg 480w, work/holiday-special-720.jpg 720w, work/holiday-special-1080.jpg 1080w',
    alt: "'Holyday Special's artwork",
    title: 'Holiday Special',
    description:
      "Charm's fundraising online event for her gender affirmation surgery fund.",
    tags: 'Sound',
    path: '/work?project=holiday-special',
    mediaTitle: `Charm's Holiday Special Show | Especial de Natal da Charm`,
    mediaSrc: 'https://www.youtube.com/embed/wWxVOTqTSts',
    year: 2020,
    credits: [
      { role: 'Produced by', people: 'Charm, Troels Primdahl & Lie Ning' },
      { role: 'DOP', people: 'Rick Kleeßen' },
      { role: 'Focus', people: 'Maximilian Carus' },
      { role: 'Sound', people: 'Nadoki Studios and Simone Antonioni' },
      { role: 'MUA', people: 'Leana Ardeleanu' },
      { role: 'Graphic Design', people: 'Ikaro Cavalcante' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'cosmic-minivan',
    ratio: '100%',
    src: 'work/cosmic-minivan-720.jpg',
    srcset:
      'work/cosmic-minivan-480.jpg 480w, work/cosmic-minivan-720.jpg 720w, work/cosmic-minivan-1080.jpg 1080w',
    alt: "'Cosmic Minivan's artwork",
    title: 'Cosmic Minivan',
    description: "Princess Century's single released on Paper Bag Records.",
    tags: 'Mix, Master',
    path: '/work?project=cosmic-minivan',
    mediaTitle: 'Princess Century - Cosmic Minivan',
    mediaSrc: 'https://www.youtube.com/embed/7qOo9FM9aCc',
    year: 2020,
    credits: [
      { role: 'Music, Written & Produced by', people: 'Maya Postepski' },
      { role: 'Directed by', people: 'Laura Hypponen' },
      { role: 'Starring', people: 'Jindalee Lehmann and Olga Fedori' },
      { role: 'DP', people: 'Johnny Welch' },
      { role: 'Editor', people: 'Chiara Armentano' },
      { role: 'Colorist & Animation', people: 'Stefano Zordan' },
      { role: 'Titles', people: 'Rosy Tsai' },
      { role: 'Production assistant', people: 'Lukas Hansen' },
      { role: 'Mix & Master', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'leon-gurvitch',
    ratio: '100%',
    src: 'work/leon-gurvitch-720.jpg',
    srcset:
      'work/leon-gurvitch-480.jpg 480w, work/leon-gurvitch-720.jpg 720w, work/leon-gurvitch-1080.jpg 1080w',
    alt: "Frame from the Jordi Garcia Rodriguez's 'Leon Gurvitch' short film",
    title: 'Leon Gurvitch',
    description: "Jordi Garcia Rodriguez's short film about Leon Gurvitch.",
    tags: 'Mix, Master',
    path: '/work?project=leon-gurvitch',
    mediaTitle: 'Leon - Belarusian-Soviet composer',
    mediaSrc: 'https://player.vimeo.com/video/486987763',
    year: 2020,
    credits: [
      { role: 'Directed by', people: 'Jordi Garcia Rodriguez' },
      { role: 'Music by', people: 'Leon Gurvitch' },
      { role: 'Violins', people: 'Ksenia Dubrovskaya and Olga Mashanskaya' },
      { role: 'Viola', people: 'Martin Stupka' },
      { role: 'Violoncello', people: 'Emilia Lomakova' },
      { role: 'Flute', people: 'Ramón Lazzaroni' },
      { role: 'Percussion', people: 'B. Abdul-Salam' },
      { role: 'Mix & Master', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli', 'João Rodrigues'],
  },
  {
    url: 'perle',
    ratio: '100%',
    src: 'work/perle-720.jpg',
    srcset:
      'work/perle-480.jpg 480w, work/perle-720.jpg 720w, work/perle-1080.jpg 1080w',
    alt: "'Perle's artwork",
    title: 'Perle',
    description: "Seleminga's first fragment of her Curvas Peligrosas' EP.",
    tags: 'Mix, Master',
    path: '/work?project=perle',
    mediaTitle: 'Seleminga - Perle',
    mediaSrc: 'https://www.youtube.com/embed/s0JjHurRb9U',
    year: 2020,
    credits: [
      { role: 'Director', people: 'Tomàs Eyzaguirre' },
      { role: 'Assistant Director', people: 'Patricio Trim' },
      { role: 'Produced & Music by', people: 'Seleminga' },
      { role: 'DOP', people: 'Jascha Müller-Guthof' },
      {
        role: 'Stylism',
        people:
          'Camille Pailler, Luisa Lauber, Helena Stölting, Ekaterine Gogashvilin & Laurențiu Dragotă',
      },
      { role: 'Hair and Make up', people: 'Samantha Pottmaier' },
      { role: 'H and M Assistant', people: 'Elisa Lange' },
      {
        role: 'Casting',
        people:
          'Jean-Cedric Sow, Odessa Kulwanowski, Giulia Gr, Lev & Seleminga',
      },
      { role: 'Editing and Color Grading', people: 'Agustín Farias' },
      { role: 'Pictures', people: 'Tomàs Eyzaguirre and Ivo Santos' },
      { role: 'Mix & Master', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'desolator',
    ratio: '100%',
    src: 'work/desolator-720.jpg',
    srcset:
      'work/desolator-480.jpg 480w, work/desolator-720.jpg 720w, work/desolator-1080.jpg 1080w',
    alt: "'Desolator's artwork",
    title: 'Desolator',
    description: "Karlo Wanny's second EP released on Us & Them Records.",
    tags: 'Master',
    path: '/work?project=desolator',
    mediaTitle: 'Desolator EP by Karlo Wanny',
    mediaSrc: 'https://open.spotify.com/embed/album/3ZDtf23MW76hnni9425qf1',
    mediaHeight: 152,
    year: 2020,
    credits: [
      { role: 'Music & Mix by', people: 'Karlo Wanny' },
      { role: 'Master', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'pharlight',
    ratio: '100%',
    src: 'work/pharlight-720.jpg',
    srcset:
      'work/pharlight-480.jpg 480w, work/pharlight-720.jpg 720w, work/pharlight-1080.jpg 1080w',
    alt: "'Pharlight' artwork made by Maik Siemer",
    title: 'Pharlight',
    description:
      "Vocal-based granular instrument developed by the team behind STRAYLIGHT for Native Instrument's Komplete.",
    tags: 'Sample Production',
    path: '/work?project=pharlight',
    mediaTitle: 'Introducing PHARLIGHT | Native Instruments',
    mediaSrc: 'https://www.youtube.com/embed/lTmvn-Zig5s',
    year: 2020,
    credits: [
      {
        role:
          'Product Concept, Design, Programming Library Concept & Production',
        people: 'Frank Elting',
      },
      {
        role: 'Vocal Artists',
        people:
          'Eva Thärichen, Pat Appleton, Ksenija Ladic, Beatboxartist Mando, Anselm Ndoung & Bodek Jahnke',
      },
      {
        role: 'Sample Content Production',
        people: 'Frank Elting, Nadoki Studios and Arovane',
      },
      {
        role: 'Sound Presets',
        people:
          'Arovane, Andreas Koslik, Jamie Wilder, Jeremiah Savage, Jeremy Leaird-Koch, Joerg Huettner, John Valasis, Ksenija Ladic, Noah Pred, Patrick Burniston, The Solos & Frank Elting',
      },
      { role: 'Quality Assurance', people: 'Francesco Sabatini' },
      { role: 'Artwork', people: 'Maik Siemer' },
    ],
    teamMembers: ['Julia Borelli', 'João Rodrigues'],
  },
  {
    url: 'sin-thetik',
    ratio: '100%',
    src: 'work/sin-thetik-720.jpg',
    srcset:
      'work/sin-thetik-480.jpg 480w, work/sin-thetik-720.jpg 720w, work/sin-thetik-1080.jpg 1080w',
    alt: "Frame from Prada's Spring /Summer 2021 Womenswear YouTube video",
    title: 'Sin Thetik',
    description:
      "Richie Hawtin's original soundtrack for Prada's Spring /Summer 2021 Womenswear.",
    tags: 'Master',
    path: '/work?project=sin-thetik',
    mediaTitle: 'Prada Spring/Summer 2021 Womenswear Show',
    mediaSrc: 'https://www.youtube.com/embed/RCQxPSNzU2Q',
    year: 2020,
    credits: [
      {
        role: 'Music by',
        people: 'Richie Hawtin',
      },
      { role: 'Master', people: 'Nadoki Studios' },
      { role: 'Co-Creative Directors', people: 'Raf Simons and Miuccia Prada' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'ovoo',
    ratio: '100%',
    src: 'work/ovoo-720.jpg',
    srcset:
      'work/ovoo-480.jpg 480w, work/ovoo-720.jpg 720w, work/ovoo-1080.jpg 1080w',
    alt: "'Ovoo' project artwork",
    title: 'Ovoo',
    description:
      '360º visual project by Ali M. Demirel in collaboration with Arts Council of Mongolia and TodaysArt.',
    tags: 'Sountrack',
    path: '/work?project=ovoo',
    mediaTitle: 'Ovoo by Ali M. Demirel',
    mediaSrc: 'https://www.instagram.com/p/CCTc4aqI7HJ/embed/',
    year: 2020,
    credits: [
      { role: 'Project by', people: 'Ali M. Demirel' },
      { role: 'Produced by', people: 'Arts Council of Mongolia + TodaysArt' },
      {
        role: 'Soundtrack by',
        people: 'Carlota Marques, Emilio Arias & Nadoki Studios',
      },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'bold-gestures',
    ratio: '100%',
    src: 'work/bold-gestures-720.jpg',
    srcset:
      'work/bold-gestures-480.jpg 480w, work/bold-gestures-720.jpg 720w, work/bold-gestures-1080.jpg 1080w',
    alt: "'Bold Gestures' podcast cover art",
    title: 'Bold Gestures',
    description:
      'A podcast where three friends attempt to make sense of this bizarro world and the people who live in it.',
    tags: 'Post-Production',
    path: '/work?project=bold-gestures',
    mediaTitle: 'Bold Gestures by Rich, Hank and Tobi',
    mediaSrc:
      'https://open.spotify.com/embed-podcast/show/2BJpkoJl24es7GCKvVo8uZ',
    year: 2020,
    credits: [
      { role: 'Podcasters', people: 'Rich, Hank and Tobi' },
      { role: 'Produced by', people: 'VGL Marketing' },
      { role: 'Co-Produced & Post-production by', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'ambrosia',
    ratio: '100%',
    src: 'work/ambrosia-720.jpg',
    srcset:
      'work/ambrosia-480.jpg 480w, work/ambrosia-720.jpg 720w, work/ambrosia-1080.jpg 1080w',
    alt: "'Ambrosia' album cover art",
    title: 'Ambrosia',
    description: "SOEL's debut album on ORACOLO Records. ",
    tags: 'Master',
    path: '/work?project=ambrosia',
    mediaTitle: 'Ambrosia by SOEL',
    mediaSrc: 'https://open.spotify.com/embed/album/7MUXZB7K88izSQvbXrJ2vo',
    mediaHeight: 300,
    year: 2020,
    credits: [
      { role: 'Music & Mix by', people: 'SOEL' },
      { role: 'Master', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli', 'João Rodrigues'],
  },
  {
    url: 'we-gotta-live-together',
    ratio: '100%',
    src: 'work/we-gotta-live-together-720.jpg',
    srcset:
      'work/we-gotta-live-together-480.jpg 480w, work/we-gotta-live-together-720.jpg 720w, work/we-gotta-live-together-1080.jpg 1080w',
    alt: "'We Gotta Live Together' album cover art",
    title: 'We Gotta Live Together',
    description: "DJ FLAT's debut single.",
    tags: 'Master',
    path: '/work?project=we-gotta-live-together',
    mediaTitle: 'We Gotta Live Together by DJ Flat',
    mediaSrc: 'https://open.spotify.com/embed/track/0v2IrjcP4tPmMWRkCBSkCk',
    year: 2020,
    credits: [
      { role: 'Music & Mix by', people: 'DJ Flat' },
      { role: 'Master', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli', 'Elia Bertolaso'],
  },
  {
    url: 'glitter-against-terfs',
    ratio: '100%',
    src: 'work/glitter-against-terfs-720.jpg',
    srcset:
      'work/glitter-against-terfs-480.jpg 480w, work/glitter-against-terfs-720.jpg 720w, work/glitter-against-terfs-1080.jpg 1080w',
    alt: "'Glitter Against Terfs' EP cover art",
    title: 'Glitter Against Terfs',
    description: "Lazy Rosario's fourth EP.",
    tags: 'Master',
    path: '/work?project=glitter-against-terfs',
    mediaTitle: 'Glitter Against Terfs EP by Lazy Rozario',
    mediaSrc: 'https://open.spotify.com/embed/album/5zWKcWRiCURalAmtGoHJkK',
    mediaHeight: 152,
    year: 2020,
    credits: [
      { role: 'Music & Mix by', people: 'Lazy Rozario' },
      { role: 'Master', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'above-it-all',
    ratio: '100%',
    src: 'work/above-it-all-720.jpg',
    srcset:
      'work/above-it-all-480.jpg 480w, work/above-it-all-720.jpg 720w, work/above-it-all-1080.jpg 1080w',
    alt: "'Above It ALL' album cover art",
    title: 'Above It All',
    description:
      'Mind Against contribution for Unity — a symbol of togetherness curated by Tale Of Us.',
    tags: 'Master',
    path: '/work?project=above-it-all',
    mediaTitle: 'AL037 - Mind Against - Above It All',
    mediaSrc: 'https://open.spotify.com/embed/track/5AS5XR6Kf2nD04B7Deqh6G',
    year: 2020,
    credits: [
      { role: 'Music & Mix by', people: 'Mind Against' },
      { role: 'Master', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli', 'Elia Bertolaso'],
  },
  {
    url: 'parda',
    ratio: 'calc(1414 / 1000 * 100%)',
    src: 'work/parda-720.jpg',
    srcset:
      'work/parda-480.jpg 480w, work/parda-720.jpg 720w, work/parda-1080.jpg 1080w',
    alt: "'Parda' documentary cover art",
    title: 'Parda',
    description: 'A Brazilian documentary, directed by Tai Linhares.',
    tags: '5.1 Mix',
    path: '/work?project=parda',
    mediaTitle: 'Parda by Tai Linhares',
    mediaSrc: 'https://player.vimeo.com/video/307440642',
    year: 2019,
    credits: [
      { role: 'Directed, Written and Produced by', people: 'Tai Linhares' },
      {
        role: 'Directors of Photography',
        people: 'Aline Juárez, Marcos Lamoreux and Sanni Est',
      },
      { role: 'Assistant Director', people: 'João Xavi' },
      { role: 'Editors', people: 'Tai Linhares and Sully Ceccopieri' },
      { role: 'Music by', people: 'The Cosmic Race' },
      { role: 'Location Sound', people: 'Elissa Brito' },
      { role: 'Sound Editor', people: 'Caio Cesar Loures' },
      { role: '2.0 Mix by', people: 'Mariana Bahia' },
      { role: '5.1 Mix by', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli', 'João Rodrigues'],
  },
  {
    url: 'love-hurts',
    ratio: '100%',
    src: 'work/love-hurts-720.jpg',
    srcset:
      'work/love-hurts-480.jpg 480w, work/love-hurts-720.jpg 720w, work/love-hurts-1080.jpg 1080w',
    alt: "'Love Hurts' single cover art",
    title: 'Love Hurts',
    description: "Osaka88's debut single.",
    tags: 'Mix, Master',
    path: '/work?project=love-hurts',
    mediaTitle: 'Love Hurts by Osaka88',
    mediaSrc: 'https://open.spotify.com/embed/track/1ClR5vHqlOlK6fj6hLKnNY',
    year: 2019,
    credits: [
      { role: 'Lyrics and Performance', people: 'Osaka88' },
      { role: 'Producer', people: '80root' },
      { role: 'Recording', people: 'Mo$sart' },
      { role: 'Mix & Master', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli', 'João Rodrigues'],
  },
  {
    url: 'der-hauptbahnhof',
    ratio: 'calc(1415 / 1000 * 100%)',
    src: 'work/der-hauptbahnhof-720.jpg',
    srcset:
      'work/der-hauptbahnhof-480.jpg 480w, work/der-hauptbahnhof-720.jpg 720w, work/der-hauptbahnhof-1080.jpg 1080w',
    alt: "'Der Hauptbanhof' documentary cover art",
    title: 'Der Hauptbanhnof',
    description:
      'A documentary written, directed and filmed by Jordi Garcia Rodriguez.',
    tags: 'Sound Design, Post-Production',
    path: '/work?project=der-hauptbahnhof',
    mediaTitle: 'AfrikaBurn – Der Hauptbahnhof',
    mediaSrc: 'https://player.vimeo.com/video/265019323',
    year: 2018,
    credits: [
      {
        role: 'Written, Directed & Filmed by',
        people: 'Jordi Garcia Rodriguez',
      },
      { role: 'Text Editor & Narrator', people: 'Lyz Pfister' },
      {
        role: 'Sound Mix & Sound Design',
        people: 'Claudine Fanilia & Nadoki Studios',
      },
      {
        role: 'Music',
        people:
          'Cal Kahoone, Thor Rixon with James Tuft, Wagner, Tchaikovsky & Xavier',
      },
      {
        role: 'Drone Footage',
        people: 'Skyhook',
      },
      {
        role: 'Extra Footage',
        people: 'Ryan Frame & Patrick Baumhöfer',
      },
    ],
    teamMembers: ['Julia Borelli'],
  },
  {
    url: 'ertrinken',
    ratio: 'calc(563 / 1000 * 100%)',
    src: 'work/ertrinken-720.jpg',
    srcset:
      'work/ertrinken-480.jpg 480w, work/ertrinken-720.jpg 720w, work/ertrinken-1080.jpg 1080w',
    alt: "Frame from 'Ertrinken' short film",
    title: 'Ertrinken',
    description:
      'A short story directed by Pedro Harres and produced by Cléo Campe.',
    tags: 'Sound Design',
    path: '/work?project=ertrinken',
    mediaTitle: 'Ertrinken / Vermächtnisstudie von DIE ZEIT, infas, WZB',
    mediaSrc: 'https://www.youtube.com/embed/aeJUNTx6fio',
    year: 2017,
    credits: [
      { role: 'Director', people: 'Pedro Harres' },
      { role: 'Executive Producer', people: 'Cléo Campe' },
      { role: 'Assistant Direction and Storyboard', people: 'Maria Teixeira' },
      { role: 'Sound Design', people: 'Nadoki Studios' },
    ],
    teamMembers: ['Julia Borelli'],
  },
]

export default workContent
